theme = "hugo-notepadium"
baseurl = "https://sat8bit.github.io/"
title = "三日坊主。"
paginate = 10
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
hasCJKLanguage = true

# Optional
# If you use googleAnalytics, you set top-level options in config.toml to the beginning of the config file like other top-level options.
googleAnalytics = "G-62G1T8FBSZ"

[Author]
  name = "Satoshi Koizumi"

[outputs]
  section = ["JSON", "HTML"]

[params]
  mainSections = ["posts", "logs"]


[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

[params.profile]
  enable = true
  name = "Satoshi Koizumi"
  twitter = "sat8bit" 
  github = "sat8bit"
  email = "sat8bit@mail.com"